<template lang="pug">
  q-card.avatar1-card.bg-c-grey-1(flat :style="`width:${avatar_width}px;height:${avatar_width}px`")
    q-card-section(style="padding:0px 0px" align="center" :class="group_members && group_members.length < 5 ? '' : 'hidden'")
      q-avatar(:style="`width:${(avatar_width-2)/2}px;height:${(avatar_width-2)/2}px`" :class="group_members && group_members[3] ? '' : 'hidden'")
        img(:src="group_members && group_members[3] ? (group_members[3].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[3].memberPeerId] ? ($store.state.linkmanMap[group_members[3].memberPeerId].avatar ? $store.state.linkmanMap[group_members[3].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/2}px;height:${(avatar_width-2)/2}px`" :class="group_members && group_members[2] ? '' : 'hidden'")
        img(:src="group_members && group_members[2] ? (group_members[2].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[2].memberPeerId] ? ($store.state.linkmanMap[group_members[2].memberPeerId].avatar ? $store.state.linkmanMap[group_members[2].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/2}px;height:${(avatar_width-2)/2}px`" :class="group_members && group_members[1] ? '' : 'hidden'")
        img(:src="group_members && group_members[1] ? (group_members[1].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[1].memberPeerId] ? ($store.state.linkmanMap[group_members[1].memberPeerId].avatar ? $store.state.linkmanMap[group_members[1].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/2}px;height:${(avatar_width-2)/2}px`" :class="group_members && group_members[0] ? '' : 'hidden'")
        img(:src="group_members && group_members[0] ? (group_members[0].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[0].memberPeerId] ? ($store.state.linkmanMap[group_members[0].memberPeerId].avatar ? $store.state.linkmanMap[group_members[0].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
    q-card-section(style="padding:0px 0px" align="center" :class="group_members && group_members.length > 4 ? '' : 'hidden'")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[8] ? '' : 'hidden'")
        img(:src="group_members && group_members[8] ? (group_members[8].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[8].memberPeerId] ? ($store.state.linkmanMap[group_members[8].memberPeerId].avatar ? $store.state.linkmanMap[group_members[8].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[7] ? '' : 'hidden'")
        img(:src="group_members && group_members[7] ? (group_members[7].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[7].memberPeerId] ? ($store.state.linkmanMap[group_members[7].memberPeerId].avatar ? $store.state.linkmanMap[group_members[7].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[6] ? '' : 'hidden'")
        img(:src="group_members && group_members[6] ? (group_members[6].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[6].memberPeerId] ? ($store.state.linkmanMap[group_members[6].memberPeerId].avatar ? $store.state.linkmanMap[group_members[6].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[5] ? '' : 'hidden'")
        img(:src="group_members && group_members[5] ? (group_members[5].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[5].memberPeerId] ? ($store.state.linkmanMap[group_members[5].memberPeerId].avatar ? $store.state.linkmanMap[group_members[5].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[4] ? '' : 'hidden'")
        img(:src="group_members && group_members[4] ? (group_members[4].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[4].memberPeerId] ? ($store.state.linkmanMap[group_members[4].memberPeerId].avatar ? $store.state.linkmanMap[group_members[4].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[3] ? '' : 'hidden'")
        img(:src="group_members && group_members[3] ? (group_members[3].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[3].memberPeerId] ? ($store.state.linkmanMap[group_members[3].memberPeerId].avatar ? $store.state.linkmanMap[group_members[3].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[2] ? '' : 'hidden'")
        img(:src="group_members && group_members[2] ? (group_members[2].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[2].memberPeerId] ? ($store.state.linkmanMap[group_members[2].memberPeerId].avatar ? $store.state.linkmanMap[group_members[2].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[1] ? '' : 'hidden'")
        img(:src="group_members && group_members[1] ? (group_members[1].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[1].memberPeerId] ? ($store.state.linkmanMap[group_members[1].memberPeerId].avatar ? $store.state.linkmanMap[group_members[1].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
      q-avatar(:style="`width:${(avatar_width-2)/3}px;height:${(avatar_width-2)/3}px`" :class="group_members && group_members[0] ? '' : 'hidden'")
        img(:src="group_members && group_members[0] ? (group_members[0].memberPeerId === $store.state.myselfPeerClient.peerId ? ($store.state.myselfPeerClient.avatar ? $store.state.myselfPeerClient.avatar : $store.defaultActiveAvatar) : ($store.state.linkmanMap[group_members[0].memberPeerId] ? ($store.state.linkmanMap[group_members[0].memberPeerId].avatar ? $store.state.linkmanMap[group_members[0].memberPeerId].avatar : $store.defaultActiveAvatar) : $store.defaultDisabledAvatar)) : ''")
    q-badge(v-if="unReadCount" color="red" floating) {{ unReadCount }}
</template>
<script src="./groupAvatar.vue.js" />
<style lang="stylus">
  .avatar1-card{ width:66px;height:66px;line-height :1}
</style>